Repository tgstation/tgui-core, pull requests merged in 2025-01, with the labels that each got.

#50 Port `Pointer` & `Interactive` from BeeStation for ColorPicker
  lib/common/color.ts
  lib/components/Interactive.tsx
  lib/components/Pointer.tsx
  lib/components/index.ts
Labels: CI Cleared

#51 Fix Dropown autoscroll
  lib/components/Dropdown.tsx
Labels: CI Cleared

#53 Little `ImageButton` tweaks
  lib/components/DmIcon.tsx
  lib/components/ImageButton.tsx
  lib/styles/components/ImageButton.scss
  stories/ImageButton.stories.tsx
Labels: CI Cleared

#55 Allow to set child styles in `Collapsible`
  lib/components/Collapsible.tsx
  stories/Collapsible.stories.tsx
Labels: CI Cleared

#59 Paint storybook to dark
  .storybook/preview.scss
  .storybook/preview.ts
  .storybook/previewTheme.ts
  package.json
  pnpm-lock.yaml
Labels: CI Cleared

#60 Fix Storybook styles import
  .storybook/preview.scss
Labels: CI Approval Required

#61 Fixes icon-only button extra padding
  lib/components/Button.tsx
  stories/Button.stories.tsx
Labels: CI Cleared

#62 Fix ImageButton border radius
  lib/components/ImageButton.tsx
  stories/ImageButton.stories.tsx
Labels: CI Cleared

#63 Add asset image scaling to `ImageButton`
  lib/components/Image.tsx
  lib/components/ImageButton.tsx
  styles/components/ImageButton.scss
Labels: CI Cleared

#66 Fix `inline` prop conflict
  lib/components/Flex.tsx
Labels: CI Cleared

#65 Bump `Dimmer` & `Tooltip` z-index
  styles/components/Dimmer.scss
  styles/components/Tooltip.scss
Labels: CI Cleared

#69 allows some events from modal
  lib/components/Modal.tsx
Labels: CI Approval Required

#74 bunch of key helpers
  lib/common/keys.ts
Labels: CI Approval Required, CI Cleared

#73 We sometimes have fictional companies
  lib/common/string.ts
Labels: CI Approval Required

#71 InfinitePlane Typescript
  lib/components/InfinitePlane.tsx
Labels: CI Cleared

#79 Fix `Button` ellipsis & `Stack.Item` overgrowing
  lib/components/Button.tsx
  lib/components/Flex.tsx
  stories/Button.stories.tsx
  styles/components/Button.scss
Labels: CI Approval Required
